Setting reconstruct and error type
OshinoShinobu-Chan/str2table pull request #2
Opened 2024-08-02 15:37 UTC by ZZH-qwq

Main contents:
- Reconstructed the validate functions in `Setting` module with `regex` / by @OshinoShinobu-Chan 
- Added `Error` module with `ArgError`, `Conflicts`, and `RangeError` for various error types / by @OshinoShinobu-Chan 
- Added some tests for `validate_force_parse()` function / by @ZZH-qwq

2024-08-03 01:21 UTC, OshinoShinobu-Chan commented
I expect to have more tests for other validation functions. Maybe we can do it in next PR.

2024-08-03 01:28 UTC, OshinoShinobu-Chan requested changes
Tests for other two validation functions should be added.

2024-08-08 10:25 UTC, OshinoShinobu-Chan approved these changes

2024-08-29 04:59 UTC, kkogoro approved these changes

2024-09-03 11:28 UTC, merged